# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies Demo
pod 'NVActivityIndicatorView'
pod 'Kingfisher'
pod 'ReachabilitySwift'

  target 'Movies DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Movies DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
